### ISSUE TITLE
Errors on browser console: npm/eslint undefined

### ISSUE THREAD

**Issue by serkandurusoy** [East5th/check-checker#1]
When I add this package, the browser console consistently displays:
- Uncaught ReferenceError: Npm is not defined
- Uncaught TypeError: Cannot read property 'eslint' of undefined

![image](https://cloud.githubusercontent.com/assets/4649948/9155430/5e473d86-3ec1-11e5-9898-647c39ff766e.png)

**Comment by pcorey** [comment]
Fixed. Try updating to 0.0.4.

**Comment by serkandurusoy** [comment]
I can confirm that. Thanks!
