### ISSUE TITLE
   error: Could not find mainModule for 'web.browser' architecture: startup/client/index.js

### ISSUE THREAD

**Issue by ivan133** [East5th/check-checker#12]
=> Errors prevented startup:                  
   
   While building the application:
   error: Could not find mainModule for 'web.browser' architecture: startup/client/index.js
   Check the "meteor" section of your package.json file?

Here is mine package.json

```
  "meteor": {
    "mainModule": {
      "client": "startup/client/index.js",
      "server": "startup/server/index.js"
    }
  },
```

I've tried to remove "client": "startup/client/index.js" for a test but it still tries to parse ui components
   ui/components/tableEditor/Cell.js:59:37: Parsing error: Unexpected token
   ui/components/tableEditor/Table.js:179:13: Parsing error: Unexpected token

Maybe I just confused  little help would be appreciated
I'm using METEOR@1.8.1

**Comment by pcorey** [comment]
Hey @ivan133, `check-checker` is a plugin, so it'll swill crawl through `Cell.js` and `Table.js` even if they're not included in your bundle.

Are you sure this error is coming from `check-checker`? I don't see anything in that error message that looks familiar, or stands out as coming from `check-checker`. Also, are there syntax errors `Cell.js:59:37` or `Table.js:179:13`?

**Comment by ivan133** [comment]
Oh
It uses new syntax:

>     if (this.props.readOnlyCellNames?.includes?.(name)) {

**Comment by pcorey** [comment]
Does Meteor support null propagation yet? I just tried to use it in a brand new `1.8.1` project, and I'm getting syntax errors in the client:

```
Template.hello.onCreated(function helloOnCreated() {
  // counter starts at 0
  this.counter = new ReactiveVar(0);
  console.log(this.nullProp?.works);
});
```

```
Uncaught SyntaxError: Unexpected token .
```

What version of Meteor are you running, and/or how did you get null propagation working in your project?

**Comment by ivan133** [comment]
There is no out-of-the box support of optional chaining

I've set it up via adding https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining in my package.json

```
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.55",
    "@babel/plugin-proposal-decorators": "^7.0.0-beta.55",
    "@babel/plugin-proposal-optional-chaining": "^7.2.0",
```

and to .babelrc
```
{
  "plugins": [
    "@babel/plugin-proposal-optional-chaining"
  ]
}
```

My meteor is 1.8.1

I guess you can just say babel plugins are not supported

**Comment by pcorey** [comment]
Yeah, it looks that way. Sorry about that. Closing this for now, as I'm not sure how to fix it.
