### ISSUE TITLE
Package checks for what subscription passes, not what publication accepts

### ISSUE THREAD

**Issue by serkandurusoy** [East5th/check-checker#2]
Given the following example:

``` javascript
if (Meteor.isClient) Meteor.subscribe('fooPub', 'foo');
if (Meteor.isServer) Meteor.publish('fooPub', function(){return Foo.find()});
```

I see the following on the server console

```
Exception from sub fooPub id xxxxxxxxx Error: Did not check() all arguments during publisher 'fooPub'
```

This is nice in a way that I'm also now aware of the unused leftover params in my subscribe calls, but just wanted to check - _no pun intended ;)_ - in with you if this is how you intended this packaged to work.

**Comment by pcorey** [comment]
Hey Serkan,

`check-checker` shouldn't be throwing exceptions like that. That looks like it's coming from `audit-argument-checks`. Are you using that package?

**Comment by serkandurusoy** [comment]
Hm, yes that's definitely correct!

I've been keeping that as well to _be on the safe side_ and I guess it kind of helped.

So come to think of it, it is like the packages now supplement each other, what do you think?

**Comment by pcorey** [comment]
Yeah, that's a good point. `check-checker` does a static check at compile time, and `audit-argument-checks` will do run time checks to catch _extra_ arguments you're passing into publications/methods.

I'll add a bit in the readme about this.

Thanks!

**Comment by pcorey** [comment]
Done. Thanks again. I hope the package is working out for you!

**Comment by serkandurusoy** [comment]
Wow, great! I'm glad I could contribute in some way or another. It is working out well for me and it definitely will be a standard in my toolset.
