### ISSUE TITLE
ESLint Plugin

### ISSUE THREAD

**Issue by dferber90** [East5th/check-checker#5]
I've started development of an ESLint Plugin for Meteor. The advantage is that it will be possible to lint the Meteor project without `meteor lint`. This way linting can be done directly in the editor.

Later on, we can develop one Meteor package that runs ESLint with the ESLint-plugin-Meteor. This way the project's configuration can be shared by the editor and the Meteor package.

Maybe you want to join the effort?
https://github.com/dferber90/eslint-plugin-meteor

**Comment by pcorey** [comment]
Very cool. It would be cool to build the package in such a way that is supports "rule plugins", so developers can develop and maintain their own rules. Rules could be added to projects through a `meteor add my-rule`.

**Comment by dferber90** [comment]
Thanks :)

I already figured most of that "plug and go" out, but I'm taking a different path. I'll release an article on it soon, because there really is a lot to consider. I'll try to remember to post it here when it's released :)

If you want to make sure you see it, you can follow me [@dferber90](https://twitter.com/@dferber90).
