### ISSUE TITLE
Object [object Object] has no method 'getFileOptions'

### ISSUE THREAD

**Issue by stolinski** [East5th/check-checker#9]
Getting this error in Meteor 1.3 beta-11 & check-checker@0.2.0

```
   While linting files with east5th:check-checker for the app (Server):
   /tools/isobuild/build-plugin.js:476:14: Object [object Object] has no method 'getFileOptions'
   at [object Object].error (/tools/isobuild/build-plugin.js:476:14)
   at packages/check-checker/lib/check-checker.js:42:1
   at Array.forEach (native)
   at packages/check-checker/lib/check-checker.js:41:1
   at Array.forEach (native)
   at CheckChecker.processFilesForPackage (packages/check-checker/lib/check-checker.js:27:1)
```

**Comment by pcorey** [comment]
Very weird. Thanks for reporting this. I'll take a look as soon as I can.

**Comment by stolinski** [comment]
Forsure. Wasn't sure if it was just a Beta-11 thing or not, figured you should know either way. Thanks for your work, love Check-checker.

**Comment by pcorey** [comment]
Looks like it's an issue with [all linters](https://github.com/meteor/meteor/issues/6414) with `beta-11` and `beta-12`. Hopefully they'll document the API changes so I can fix this before the upcoming release!
